import { createElement } from 'lwc';
import AssignmentWeek12_Q3_FamousPeople from 'c/assignmentWeek12_Q3_FamousPeople';

describe('c-assignment-week12-q-3-famous-people', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-assignment-week12-q-3-famous-people', {
            is: AssignmentWeek12_Q3_FamousPeople
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});