import { createElement } from 'lwc';
import Calculator_AssignmentWeek_12 from 'c/calculator_AssignmentWeek_12';

describe('c-calculator-assignment-week-12', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-calculator-assignment-week-12', {
            is: Calculator_AssignmentWeek_12
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});