//INSERT Standard object
DmlDemo.dmlInsertDemo_stdnObj();

//INSERT Custom Object
DmlDemo.dmlInsertDemo_cstmObj();

//UPDATE Standard Object
DmlDemo.dmlUpdateDemo_1();

//UPDATE-2 (First SOQL then UPDATE data)
DmlDemo.dmlUpdateDemo_3();

//INSERT for related(master-detail) Objects(contact and account)
DmlDemo.dmlUpdateDemo_2();

//INSERT for related CURTOM Objects(Project and Ticket)
DmlDemo.dmlUpdateDemo_2_CO();

// INSERT Multiple record by using LIST
DmlDemo.dmlMultipleRecordInsert_right();