public class PostalResponseWrapper{
            @AuraEnabled
            public string Name;
            @AuraEnabled
            public string Description;
            @AuraEnabled
            public string PINCode;
            @AuraEnabled
            public string BranchType;
            @AuraEnabled
            public string DeliveryStatus;
            @AuraEnabled
            public string Circle;
            @AuraEnabled
            public string District;
            @AuraEnabled
            public string Division;
            @AuraEnabled
            public string Region;
            @AuraEnabled
            public string State;
            @AuraEnabled
            public string Country;
           
           
        }
