public class MathmaticalClass {
    public static integer addition(integer a, integer b) {

        Integer num1 = a;
        Integer num2 = b;
            Integer sum = a + b;
            return sum;
            
    }
    public static integer subtraction(integer c, integer d) {

        Integer num3 = c;
        Integer num4 = d;
            Integer sub = c - d;
            return sub;
    }
    public static integer multiplication(integer e, integer f) {

        Integer num5 = e;
        Integer num6 = f;
            Integer multi = e * f;
            return multi;
    }
    public static integer division(integer g, integer h) {

        Integer num7 = g;
        Integer num8 = h;
            Integer div = g / h;
            return div;
    }
}
