import { createElement } from 'lwc';
import ADAPTER_getObjectInfo_Opportunity from 'c/aDAPTER_getObjectInfo_Opportunity';

describe('c-a-d-a-p-t-e-r-get-object-info-opportunity', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-a-d-a-p-t-e-r-get-object-info-opportunity', {
            is: ADAPTER_getObjectInfo_Opportunity
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});